-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 19, 2019 at 05:33 AM
-- Server version: 10.4.10-MariaDB
-- PHP Version: 7.1.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ktd`
--

-- --------------------------------------------------------

--
-- Table structure for table `doctors`
--

CREATE TABLE `doctors` (
  `id` int(11) NOT NULL,
  `name` varchar(200) NOT NULL,
  `qualification` varchar(200) NOT NULL,
  `certification` varchar(200) NOT NULL,
  `specialty` varchar(200) NOT NULL,
  `medicalSchool` varchar(200) NOT NULL,
  `hospitalAffiliation` varchar(200) NOT NULL,
  `residency_fellowship` varchar(200) NOT NULL,
  `biography` text NOT NULL,
  `image` varchar(300) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `doctors`
--

INSERT INTO `doctors` (`id`, `name`, `qualification`, `certification`, `specialty`, `medicalSchool`, `hospitalAffiliation`, `residency_fellowship`, `biography`, `image`) VALUES
(23, 'Grace Dasovich', 'MD, FAAP', 'Board Certified', 'General Pediatrics and Child Development', 'University of Minnesota Medical School', 'N/A', 'University of California Irvine / Children\'s Hospital of Orange County', '<p><span style=\"font-family: OpenSans-Semibold;\">Dr. Grace Dasovich is a board certified Pediatrician who is excited to start a career at Kids & Teens Medical Group. She attended Northwestern University and obtained a Bachelor of Science degree in Biomedical Engineering. She received her medical degree from the University of Minnesota Medical School and completed her pediatrics residency at the University of California Irvine / Children’s Hospital of Orange County program. Outside of medicine, she enjoys spending time with family, traveling, and running marathons.</span><br></p>', 'e212b5325811a797ac19bb400f804f94.png'),
(24, 'Dr. Debra Barach', 'N/A', 'Board Certified', 'General Pediatrics and Child Development', 'UCLA School of Medicine', 'N/A', 'LA County-USC', '<p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Semibold;\"><span style=\"margin: 0px; padding: 0px; border: 0px; color: rgb(34, 170, 204);\">Dr. Barach was born and raised in Southern California until moving to Israel at the age of 14.  She received her Bachelor of Science in Biology, Magna Cum Laude from The Hebrew University of Jerusalem.</span></p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\"><span style=\"margin: 0px; padding: 0px; border: 0px; font-family: OpenSans-Semibold;\">Dr. Barach attended the UCLA School of Medicine and received her MD in 1985.  She completed her pediatric residency training at LA County-USC in 1988, and worked in private practice until 2006, after which she took time to raise her twin daughters.  She and her husband live in Sherman Oaks with their daughters, Sophia and Eliana.</span></p>', 'd32d57523182660a611c52191c386b91.png'),
(25, 'Amy Wagner', 'MD, FAAP', 'Board Certified', 'General Pediatrics and Child Development', 'Wake Forest University School of Medicine', 'N/A', 'Children\'s Hospital of Orange County', '<div style=\"margin: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">Dr. <span id=\"m_68670575145436630270.17085697843506265\" class=\"m_6867057514543663027highlight\" style=\"margin: 0px; padding: 0px; border: 0px;\">Wagner</span> is a board-certified pediatrician. She has been practicing for over seventeen years now. She earned her medical degree at Wake Forest University School of Medicine and received her pediatrics training at Children’s Hospital of Orange County.</div><div style=\"margin: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\"></div><div style=\"margin: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">Dr. <span id=\"m_68670575145436630270.6949641937385154\" class=\"m_6867057514543663027highlight\" style=\"margin: 0px; padding: 0px; border: 0px;\">Wagner</span> loves spending time with her two children. She jogs regularly and keeps herself busy with home renovation projects. She is an avid poker player, who loves movies of all genres, and reading real books made out of paper.</div>', 'a7d349b1070a8505d72967c4b78c2e0c.png'),
(26, 'Janesri De Silva', 'MD, FAAP', 'Board Certified', 'General Pediatrics and Child Development', 'American University of the Caribbean', 'Pediatric Department at Northridge Hospital Medical Center Valley Presbyterian Hospital Tarzana Medical Center Huntington Memorial Hospital', 'USC Yale Affiliated Hospitals, MD, IL Kaiser Permanente, Sunset Children\'s Hospital Los Angeles', '<p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Semibold;\">Dr. De Silva graduated from UCLA with a Bachelor’s degree in Neuroscience and then went on to the American University of the Caribbean to complete her medical degree.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">Listen to Dr. De Silva’s interview with KFWB talk radio, regarding medication dosage for children.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">She did part of her medical training at USC, Yale affiliated hospitals and other hospitals in Maryland and Chicago. She then completed a 3 year pediatric residency at Kaiser Permanente, Sunset. While at Kaiser, she wrote a manual for pediatric interns on how to take care of patients.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">After residency, she did a fellowship at Children’s Hospital Los Angeles in Adolescent Medicine and worked at the Los Angeles Free Clinic. At CHLA, Dr. De Silva worked on research involving transitioning chronically ill children to adult health care.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">She is the 2014 to 2016 chair of the Pediatric department at Northridge Hospital Medical Center in Northridge, and is on staff at Valley Presbyterian Hospital in Van Nuys, Tarzana Medical CenterTarzana and Huntington Memorial Hospital in Pasadena, CA.</p>', '0c0f0a6970ab48410af5802d8814a0e2.png'),
(27, 'Jose Vargas', 'P.A.', 'Board Certified', 'General Pediatrics and Child Development', 'Charles Drew University of Medicine and Science.', 'N/A', 'N/A', '<p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Semibold;\">Jose Vargas is a Physician Assistant that joined Kids and Teens in  January 2018. Jose comes to us with over 30 years of experience in Pediatric and Family Medicine. His past practices include the West Hollywood, Highland Park and Pacoima communities.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">Jose enjoys learning and meeting new challenges.  His priority is to provide high quality Pediatric care to  young children and teens in the community.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">Jose is married with two grown children.  He is very involved with many neighborhood organizations  that effect his community.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">In his free time Jose enjoys many outdoor activities such as camping, hiking and cycling. He enjoys keeping fit and attends the gym regularly.  He likes to encourage his patients and their families to get out there and exercise and to promote a healthy lifestyle</p>', '4da14e91134e33fee817bac85fb34e83.png'),
(28, 'Dr. Gaya Selvakkumaran', 'MD FAAP', 'Board Certified', 'General Pediatrics and Child Development', 'University of Zambia, School of Medicine', 'Methodist Hospital', 'White Memorial Medical Center', '<p><span style=\"font-family: OpenSans-Semibold;\">Dr Gaya (Gayathri Selvakkumaran MD FAAP), did her Medical education/training in Zambia where she treated many infectious diseases no longer prevalent in the first world countries. She then moved to UK for Neonatal fellowship training, but moved to California in the middle of it. She completed her Pediatric residency at White Memorial Medical Center, and since then been an esteemed Pediatrician working in the San Gabriel Valley area for the past 8 years. With her vast international experience in Pediatrics she provides excellent Pediatric care to her patients. In her free time she enjoys classical dancing, cooking and best of all spending time with her children; hence her maternal instincts makes her a lovable Pediatrician.</span><br></p>', 'b60b02be525f19ad91298524500e1f6e.png'),
(29, 'Kaberi Mozumder', 'PNP', 'Board Certified', 'General Pediatrics and Child Development', 'Yale School of Nursing', 'Stanford Children\'s Hospital, Children\'s Hospital of Los Angeles, and Cedars-Sinai Medical Center', 'N/A', '<p><span style=\"margin: 0px; padding: 0px; font-weight: 700; border: 0px; font-family: OpenSans-Semibold;\">Kaberi has been a pediatric nurse practitioner for over 10 years graduating from Yale School of Nursing in 2008. She has extensive experience in both the inpatient and outpatient setting. She previously worked in specialty care for pediatric cardiology and cardio-thoracic surgery at a number of large academic centers including Stanford Children’s Hospital, Children’s Hospital of Los Angeles and Cedars-Sinai Medical Center before moving into the primary and urgent care setting. She is passionate about helping children and loves working with kids of all ages. Some of her special interests include adolescent medicine, mental health, asthma, and nutrition. She is a native Southern Californian and loves serving her home community. She is fluent in Spanish and spends her free time travelling, baking and spending time with her shih tzu Timmy.</span><br></p>', '84f1834395d7e2a25d79020f5d634e44.png'),
(30, 'Dr. Margaret Zdarzyl', 'MD FAAP', 'Board Certified', 'General Pediatrics and Child Development', 'Nicolaus Copernicus University in Poland', 'USC Verdugo Hills Hospital', 'N/A', '<table border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin: 0px; padding: 0px; border-spacing: 0px; border: 0px; font-family: OpenSans-Regular;\"><tbody style=\"margin: 0px; padding: 0px; border: 0px;\"><tr style=\"margin: 0px; padding: 0px; border: 0px;\"><td class=\"tdbottomborder\" colspan=\"3\" style=\"margin: 0px; padding: 0px; border: 0px;\">Margaret Zdarzyl, MD, is board certified in pediatrics. Dr. Zdarzyl earned her medical degree from Nicolaus Copernicus University in Poland. She completed her internship and residency at White Memorial Medical Center in Los Angeles. Dr. Zdarzyl is passionate about helping children and believes deeply in patient education. She loves to ski and garden. In addition to English, Dr. Zdarzyl speaks Polish and Spanish</td></tr></tbody></table>', 'b780527911c03b717f92f21a3eb44654.png'),
(31, 'Hilma Benjamin', 'MD, FAAP', 'Board Certified', 'Pediatrics and Adolescent Medicine', 'Penn State College of Medicine', 'Northridge Hospital Medical Center Providence Tarzana Medical Center Medical Director of After-Hours Pediatric Urgent Care', 'Children\'s Hospital, St. Petersburg, FL Tampa General Hospital, Tampa, FL', '<p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Semibold;\">Dr. Hilma Benjamin graduated from the University of the Virgin Islands with a Bachelor of Science in Biology and later earned a Master’s of Science in Molecular and Cellular Biology at the University of Maryland, Baltimore County.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">She received her medical degree in 2004 from Penn State College of Medicine and completed her residency in pediatrics at All Children’s Hospital in St. Petersburg, Florida, and Tampa General Hospital in Tampa, Florida.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">Before joining Kids and Teens in 2009, she worked as locums tenens in private practice in the San Francisco Bay Area and at the Monterey County Health Department in outpatient and inpatient settings at the Natividad Medical Center, affiliated with UCSF.</p>', '9146ddf0b5392a45b8f414a44bad061d.png'),
(33, 'Victoria Millet', 'MD, FAAP', 'Board Certified', 'General Pediatrics and Infectious Disease', 'USC', 'Providence Tarzana Medical Center Northridge Hospital and Medical Center', 'University Hospital, San Diego University of California Los Angeles', '<p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Semibold;\">Dr. Millet completed her undergraduate work as a Zoology Major at the University of California at Los Angeles in 1969. She earned a Master of Science Degree at the University of Southern California which was awarded in 1972. She completed a three year residency in pediatrics at University Hospital in San Diego in 1975.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">She completed a Pediatric Infectious Diseases/Ambulatory Pediatrics fellowship at the Center for the Health Sciences, University of California at Los Angeles in 1980.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">Dr. Millet has been in private pediatric practice since 1984. She joined Kids and Teens Medical Group in January of 2011. She continues to do consulting work in pediatric infectious diseases for the Kids and Teens group, as well as for her colleagues in the local pediatric community. She also enjoys teaching and is a member of the faculty of the Family Practice Residency Program at Northridge Hospital.</p>', '1b66b70e3a6d888c33684d151c092c6a.png'),
(35, 'Priya Harder', 'MD, FAAP', 'Board Certified', 'Pediatrics and Adolescent Medicine', 'Drexel University College of Medicine', 'N/A', 'Dupont Hospital/TJUH, DE', '<p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Semibold;\">Dr. Harder was born and raised in La Canada and graduated cum laude from USC with a degree in English Literature and Language. She attended medical school at Drexel University College of Medicine <em style=\"margin: 0px; padding: 0px; border: 0px;\">(formerly MCP Hahnemann)</em>. She completed her internship and residency at Dupont Hospital for Children/TJUH in Wilmington, Delaware.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">Dr. Harder has worked in private practice in Pasadena since 2010 and presently sees newborn babies at Huntington Memorial Hospital. Dr. Harder lives in La Canada with her husband and three children, Arianna, Deven & Gregory</p>', '5ebf70ecdf9a39cb66060fbbcc5011b0.png'),
(236, 'Barbara Rodriguez', 'MD, FAAP', 'Board Certified', 'General Pediatrics and Child Development', 'Creighton University Medical School', 'N/A', 'LAC-USC', '<p><span style=\"font-family: OpenSans-Semibold;\">She attended the University of Southern California &amp; received her Bachelor of Science degree in Biological Sciences. She then attended Creighton University Medical School &amp; received her MD in 1985. She completed her Pediatric Training at LAC-USC in 1988 &amp; has been involved in Pediatric Primary Care &amp; Pediatric Urgent Care since then. She has been an active member of Creighton’s Medical Dean’s Alumni Advisory Board since 1998. She is a Fellow of the American Academy of Pediatrics &amp; a member of the American Board of Pediatrics.</span><br></p>', 'eb5e1e7d40fb777f3832c8827dc49035.png'),
(237, 'Martin Fineberg', 'MD, FAAP', 'Board Certified', 'General Pediatrics and Child Development', 'The University of Melbourne, Royal Children’s Hospital', 'N/A', 'Emory University', '<p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Semibold;\">Martin Fineberg has been with Pediatric Affiliates Medical Group, Inc. since 1988.&nbsp; A native of Melbourne, Australia he studied medicine at The University of Melbourne.&nbsp; He&nbsp;then trained in pediatrics at the Royal Children’s Hospital in Melbourne&nbsp;followed by a pediatric residency at Emory University in Atlanta. Following&nbsp;this, he undertook additional training in neonatology at Children’s Hospital Los Angeles. In addition, Dr. Fineberg worked in the area of pediatric hematology/oncology at the Prince of Wales Hospital in Sydney, Australia. Dr. Fineberg is licensed to practice medicine in California and Australia, and was board certified by the American Board of Pediatrics in 1985.&nbsp;He was re-certified in 2009 and is current with Maintenance of Certification with the American Board of Pediatrics.&nbsp;&nbsp;He is a Fellow of the American Academy of Pediatrics, a member of the California Medical Association, the American Medical Association and an American Academy member of the Canadian Paediatric Society.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">Dr. Fineberg was previously the director of the Neonatal Intensive Care Unit (NICU) at West Hills Hospital and Medical Center.&nbsp; He is now full time in general pediatrics with a special expertise and interest in the care of the high-risk NICU graduate and children with pulmonary diseases.&nbsp;&nbsp;&nbsp; He is also the Pediatric Affiliates vaccine expert</p>', '8fffe1825b26a5ec45215ab652282070.png'),
(238, 'Mark Snyder', 'MD, FAAP', 'Board Certified', 'General Pediatrics and Child Development', 'Kansas University in Kansas City', 'N/A', 'Cedars Sinai Medical Center', '<p><span style=\"font-family: OpenSans-Semibold;\">Mark Snyder is a Woodland hills native and an alum of El Camino Real High School.  He went to college at U. C. San Diego and majored in Biomedical Engineering, and he spent his junior year abroad studying at Hebrew University in Jerusalem.  He then attended medical school at Kansas University in Kansas City, but returned to L.A. for his pediatric residency at Cedars Sinai Medical Center. He was board certified in pediatrics originally in 1992, and then recertified in 1998, 2006, and in 2015, and he is a fellow of the American Academy of Pediatrics.  He loves to spend time with his family, and he also enjoys mountain biking, exercising at the gym, hiking with the family dog, following politics and world events, and reading about all of the sciences, with a special interest in astronomy and evolution.  And of course, he loves and enjoys his work as a pediatrician at Pediatric Affiliates, working in the community where he grew up and currently lives.</span><br></p>', 'd82811ae9236116e79a2d9386e73d152.png'),
(239, 'Beth Melin-Perel', 'MD, FAAP', 'Board Certified', 'General Pediatrics and Child Development', 'University of Arkansas Medical School', 'N/A', 'St. Christopher’s Hospital for Children in Philadelphia', '<p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Semibold;\">Dr. Beth Melin-Perel completed her undergraduate education at Washington University in St. Louis while on a National Merit scholarship. She graduated summa cum laude with a bachelor’s degree in biology and a minor in literature.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">She attended the University of Arkansas Medical School on a full scholarship, and went on to do her pediatric residency at St. Christopher’s Hospital for Children in Philadelphia. She was on the teaching staff at Yale University in New Haven, CT and active in private practice. She is Board Certified by the American Board of Pediatrics, and is a member of the American Academy of Pediatrics and the Los Angeles Pediatric Society.  She and her wonderful husband, Dr. Issie Perel, raised three sons who are now in graduate programs. Dr.Beth volunteers at the Westminster Free Clinic in Thousand Oaks, and enjoys gardening, movies, and healthy cooking in her leisure time.</p>', 'c8474bb5e12e0cf76ce5ea9eee8508aa.png'),
(240, 'Marianne Woods', 'MD, MSPH', 'Board Certified', 'Pediatrics and Adolescent Medicine', 'Jagiellonian University Medical College, Krakow, Poland', 'N/A', 'Kaiser Permanente, Los Angeles', '<p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Semibold;\">Dr. Woods received her MD degree from the Jagiellonian University Medical College in Krakow, Poland in 1984 and an MSPH degree from the UCLA School of Public Health in 1979. She completed her residency program in Pediatrics at Kaiser Permanente Medical Center in Los Angeles, CA in 1993 and worked as a pediatrician in the outpatient clinics of the Kaiser Permanente system for over 20 years.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">At the Kids and Teens clinics, she continues to provide high quality acute and preventative care with a special interest in nutritional guidance, weight control and anticipatory guidance</p>', 'f0c58f8effda0a5a69351fbf5b399af9.png'),
(241, 'Peter Jackson', 'MD, FAAP', 'Board Certified', 'Pediatrics and Adolescent Medicine', 'U.C., Irvine', 'N/A', 'Cedars Sinai Medical Center, Beverly Hills', '<p><span style=\"font-family: OpenSans-Semibold;\">Dr. Peter Jackson has practiced pediatrics for nearly 31 years, all in the same location in Pasadena at the Children’s Clinic now Kids & Teens Medical Group. Dr. Jackson is a Southern California native who went to medical school at U.C. Irvine and had an internship and residency at Cedar Sinai Medical Center in Beverly Hills.</span><br></p>', '48fd4f9c680db85e26e6edb92b2fbfac.png'),
(242, 'Padma Bala', 'MD, FAAP', 'Board Certified', 'Pediatrics and Adolescent Medicine', 'Madras Medical College, Madras, India', 'N/A', 'Rushy Presbyterian Medical Center, IL', '<p><span style=\"font-family: OpenSans-Semibold;\">Dr. Padma Bala, graduated from the prestigious Madras Medical College at Madras, India. She completed her Residency in Pediatrics at Rush Presbyterian Medical Center in Chicago, after which she served in US Army Medical Corps, as a Pediatrician with the Rank of Lt Colonel. She then joined Baylor Medical Group in Dallas while consistently achieving “Best Pediatrician Award” from the local Communities for many years. She moved to Los Angeles to be close to her children and grandchildren</span><br></p>', '9c5e5f53be3dfdeb0b9b3f69805fe75f.png'),
(243, 'Lourdes Mosqueda', 'MD', 'Board Certified', 'Pediatrics and Adolescent Medicine', 'University of Illinois College of Medicine, Rockford', 'N/A', 'California Pacific Medical Center, San Francisco', '<p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Semibold;\">Dr. Mosqueda&nbsp;attended the University of California, Irvine where she received her Bachelors degree in Biological Sciences. &nbsp;She attended the University of Illinois College of Medicine, Rockford where she received her medical degree. &nbsp;Dr. Mosqueda completed her Pediatric Residency training at California Pacific Medical Center in San Francisco, California.</p><p style=\"margin-right: 0px; margin-bottom: 20px; margin-left: 0px; padding: 0px; border: 0px; font-family: OpenSans-Regular;\">Dr. Mosqueda is a Pediatrician who has practiced&nbsp;medicine in San Francisco since 1997. &nbsp;In 2010,&nbsp;Dr. Mosqueda, her husband and 3 children&nbsp;moved to South Pasadena where&nbsp;she continues her commitment to children’s health. &nbsp;She sees children from birth until their 18th birthday. &nbsp;She looks forward to meeting you and your family.</p>', 'efb4febed6fa5138586948cdf736f2bf.png'),
(244, 'Orlando Ayala', ' PA-C', 'Board Certified', 'Physician Assistant', 'Physician’s Assistant at the University of Southern California', 'N/A', 'N/A', '<p><span style=\"font-family: OpenSans-Semibold;\">Orlando Ayala grew up in East Los Angeles and completed his training as physician’s assistant at the University of Southern California.&nbsp;He worked at the Clinica Medica San Miguel for 8 years prior to starting full time at Kids and Teens Medical Group.&nbsp;Mr Ayala works at the Van Nuys and Pasadena locations of Kids and Teens.&nbsp;He lives in Eagle Rock with his wife and daughter, Isabella.</span><br></p>', 'dcfa7941d6fdc44e7f7304568e9fcda1.png');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `doctors`
--
ALTER TABLE `doctors`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `doctors`
--
ALTER TABLE `doctors`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=245;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
